import { ActivityProps } from "../types/activity";

const ACTIVITY_ITEMS: ActivityProps[] = [
  {
    id: 1,
    name: "Kerja Bakti Lingkungan",
    description: "Bersama-sama membersihkan lingkungan sekitar.",
    image: "/images/activity/png",
    date: "2024-09-20",
    time: "08:00",
    location: "Taman RT 04",
    status: "akan datang",
    isShow: true,
  },
  {
    id: 2,
    name: "Rapat Bulanan RT",
    description: "Diskusi tentang perkembangan kegiatan RT.",
    image: "/images/activity/png",
    date: "2024-09-25",
    time: "19:00",
    location: "Balai RT 04",
    status: "akan datang",
    isShow: true,
  },
  {
    id: 3,
    name: "Peringatan Hari Kemerdekaan",
    description: "Acara perlombaan dan upacara 17 Agustus.",
    image: "/images/activity/png",
    date: "2024-08-17",
    time: "07:00",
    location: "Lapangan RT 04",
    status: "selesai",
    isShow: true,
  },
  {
    id: 4,
    name: "Senam Pagi",
    description: "Senam bersama untuk kesehatan warga.",
    image: "/images/activity/png",
    date: "2024-09-18",
    time: "06:00",
    location: "Taman RT 04",
    status: "selesai",
    isShow: true,
  },
  {
    id: 5,
    name: "Posyandu Balita",
    description: "Pemeriksaan kesehatan balita.",
    image: "/images/activity/png",
    date: "2024-09-22",
    time: "09:00",
    location: "Posyandu RT 04",
    status: "akan datang",
    isShow: true,
  },
  {
    id: 6,
    name: "Gotong Royong Taman",
    description: "Memperbaiki dan merapikan taman RT.",
    image: "/images/activity/png",
    date: "2024-10-01",
    time: "07:30",
    location: "Taman RT 04",
    status: "akan datang",
    isShow: true,
  },
  {
    id: 7,
    name: "Pengajian Warga",
    description: "Pengajian rutin untuk warga sekitar.",
    image: "/images/activity/png",
    date: "2024-09-30",
    time: "17:00",
    location: "Mushola RT 04",
    status: "akan datang",
    isShow: true,
  },
];

export default ACTIVITY_ITEMS;
