const CORRESPONDENCE_ITEMS = [
  {
    title: "Surat Pengantar KTP",
    description: "Surat pengantar untuk pembuatan KTP di Kelurahan.",
    letter_no: "001/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-pengantar-ktp.pdf",
    is_show: true,
  },
  {
    title: "Surat Keterangan Domisili",
    description: "Surat keterangan domisili untuk berbagai keperluan.",
    letter_no: "002/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-keterangan-domisili.pdf",
    is_show: true,
  },
  {
    title: "Surat Keterangan Usaha",
    description: "Surat keterangan untuk pemilik usaha di lingkungan RT.",
    letter_no: "003/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-keterangan-usaha.pdf",
    is_show: true,
  },
  {
    title: "Surat Pengantar KK",
    description: "Surat pengantar untuk pembuatan Kartu Keluarga baru.",
    letter_no: "004/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-pengantar-kk.pdf",
    is_show: true,
  },
  {
    title: "Surat Keterangan Tidak Mampu",
    description: "Surat keterangan untuk keluarga kurang mampu.",
    letter_no: "005/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-keterangan-tidak-mampu.pdf",
    is_show: true,
  },
  {
    title: "Surat Pengantar Pindah Alamat",
    description: "Surat pengantar untuk kepindahan warga ke alamat baru.",
    letter_no: "006/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-pengantar-pindah-alamat.pdf",
    is_show: true,
  },
  {
    title: "Surat Keterangan Kelahiran",
    description: "Surat keterangan untuk melaporkan kelahiran anak.",
    letter_no: "007/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-keterangan-kelahiran.pdf",
    is_show: true,
  },
  {
    title: "Surat Keterangan Kematian",
    description: "Surat keterangan untuk pelaporan kematian.",
    letter_no: "008/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-keterangan-kematian.pdf",
    is_show: true,
  },
  {
    title: "Surat Pengantar Nikah",
    description: "Surat pengantar untuk keperluan administrasi pernikahan.",
    letter_no: "009/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-pengantar-nikah.pdf",
    is_show: true,
  },
  {
    title: "Surat Rekomendasi RT",
    description: "Surat rekomendasi dari Ketua RT untuk berbagai keperluan.",
    letter_no: "010/RT02/2024",
    image: "/images/hero.jpg",
    url: "/surat/surat-rekomendasi-rt.pdf",
    is_show: true,
  },
];

export default CORRESPONDENCE_ITEMS;
