import { PromotionProps } from "../types/promotion";

const PROMOTION_ITEMS: PromotionProps[] = [
  {
    title: "lorem",
    description: "lorem ipsum dolor sit amet.",
    image: "/images/react-hooks.png",
    category: "Block 1",
    imageProfile: "/images/profile1.png",
    name: "John Doe",
    date: "2024-08-25",
    isShow: true,
  },
  {
    title: "lorem",
    description: "lorem ipsum dolor sit amet.",
    image: "/images/typescript.png",
    category: "Block 1",
    imageProfile: "/images/profile2.png",
    name: "Jane Smith",
    date: "2024-08-20",
    isShow: true,
  },
  {
    title: "lorem",
    description: "lorem ipsum dolor sit amet.",
    image: "/images/nextjs.png",
    category: "Block 2",
    imageProfile: "/images/profile3.png",
    name: "Alice Johnson",
    date: "2024-08-15",
    isShow: true,
  },
  {
    title: "lorem",
    description: "lorem ipsum dolor sit amet.",
    image: "/images/nextjs.png",
    category: "Block 2",
    imageProfile: "/images/profile3.png",
    name: "Alice Johnson",
    date: "2024-08-15",
    isShow: true,
  },
  {
    title: "lorem",
    description: "lorem ipsum dolor sit amet.",
    image: "/images/nextjs.png",
    category: "Block 2",
    imageProfile: "/images/profile3.png",
    name: "Alice Johnson",
    date: "2024-08-15",
    isShow: true,
  },
  {
    title: "lorem",
    description: "lorem ipsum dolor sit amet.",
    image: "/images/nextjs.png",
    category: "Block 2",
    imageProfile: "/images/profile3.png",
    name: "Alice Johnson",
    date: "2024-08-15",
    isShow: true,
  },
];

export default PROMOTION_ITEMS;
